import './signInPage.html'
// import './signInPageEvents.js'
// import './signInPageHelpers.js'
// import './signInPageOnCreated.js'
// import './signInPageOnRendered.js'
// import './signInPageOnDestroyed.js'
// import './signInPageStyle.css'