import './signUpPage.html'
import './signUpPageEvents.js'
// import './signUpPageHelpers.js'
// import './signUpPageOnCreated.js'
// import './signUpPageOnRendered.js'
// import './signUpPageOnDestroyed.js'
// import './signUpPageStyle.css'